name: Run Minifier Tests on Commit

on:
  push:
    branches:
    - main
  
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Script Minifier Repo
      uses: actions/checkout@v4

    - name: Run tests
      shell: bash
      run: |
        python3 -m unittest discover -s src
