name: Run Test on Commit

on:
  push:
    branches:
    - main
  
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Run tests
      shell: bash
      run: |
        python3 src/script_minify_test.py
